#!/usr/bin/env python3

import gitlab;
import subprocess;

TOKEN='XXXXXXXXXXXXXXXXX'
ENDPOINT='http://git4lab8.labs.mastercard.com/gitlab8'

gl = gitlab.Gitlab(ENDPOINT, private_token=TOKEN)


def clone_project(project):
    http_url = project.http_url_to_repo
    #print(f"http {http_url}")
    name = project.name
    path = project.path
    description = project.description
    #print(f"name {name}, path: {path}, desription: {description}")
    namespace = project.namespace
    full_path = namespace['full_path']
    #print(f"full_path: {full_path}")
    print(f"name {name}, path: {path}, full_path: {full_path}, url: {http_url}")

    clone_dir=f"{full_path}/{path}"
    print(f"cloning {http_url} to {clone_dir}")

    subprocess.run(["git","clone", http_url, clone_dir])

def clone_group(group_id):

    group = gl.groups.get(group_id)

    # page=1, per_page=10
    #include_subgroups

    current_page=1
    page_size=10
    done=False
    total_projects = 0
    while not done:

      print(f"getting projects - current_page: {current_page}, page_size: {page_size}")
      projects = group.projects.list(page=current_page, per_page = page_size, include_subgroups = True)

      num_projects = len(projects)
      print(f"-> num_projects {num_projects}")

      current_page = current_page + 1
      done = num_projects == 0

      for project in projects:
        clone_project(project)
        total_projects = total_projects + 1

    print(f"total projects: {total_projects}")


clone_group('infrastructure')


